export const COLORS = {
  UCONN_NAVY: '#0E1E45',
  UCONN_WHITE: '#FFFFFF',
  UCONN_GREY: '#A7A9AC',
  UCONN_RED: '#D50032',
  HIGHLIGHT: '#FFD700',
  EVENT_COLOR: '#4A90E2',
  BUTTON_BG: '#0E1E45',
  BORDER_COLOR: '#DDDDDD',
  ERROR_COLOR: '#FF3B30'
}